### ISSUE TITLE
[Fuyctl Next] kfd.yaml optional requirements

### ISSUE THREAD

**Issue by ralgozino** [sighupio/furyctl#115]
update the dependencies definition file (kfd.yaml) with optional or required information for each dependency.

**Comment by omissis** [comment]
yaml should look like the following:

```
tools:
  ansible: 
    version: 2.13.4
    required: true
  furyagent: 
    version: 0.3.0
    required: true
  kubectl: 
    version: 1.23.10
    required: true
  kustomize: 
    version: 3.10.0
    required: true
  terraform: 
    version: 0.15.4
    required: true
```

Please remember to update:
- the schema
- the parsing code
- the validation logic, which should not fail in case a tool is not available and not required
