### ISSUE TITLE
Missing validation about nodepool size

### ISSUE THREAD

**Issue by g-iannelli** [sighupio/furyctl#253]
Missing the validation of the size of node pool when set size.min > size.max

```yaml
    nodePools:
        # This is the name of the nodepool
      - name: infra
        # This optional map defines a different AMI to use for the instances
        #ami:
        #  id: ami-0123456789abcdef0
        #  owner: "123456789012"
        # This map defines the max and min number of nodes in the nodepool autoscaling group
        size:
          min: 3
          max: 1
```
