### ISSUE TITLE
Wrong validation of spec.distribution.modules.ingress.override.ingresses

### ISSUE THREAD

**Issue by g-iannelli** [sighupio/furyctl#256]
Wrong validation of `spec.distribution.modules.ingress.override.ingresses` because the code showed below pass the validation.

```yaml
      ingress:
        # This optional key is used to override automatic parameters
        overrides:
          ingresses:
            forecastle:
              disableAuth: false
              host: forecastle.internal.example.dev
              ingressClass: alb
            internalNginx:
              disableAuth: false
              host: forecastle.internal.example.dev
              ingressClass: ngx-int
            externalNginx:
              disableAuth: false
              host: forecastle.internal.example.dev
              ingressClass: ngx-ext
``` 

While the only accepted should be [`forecastle`](https://github.com/sighupio/fury-distribution/blob/feature/furyctl-next/schemas/ekscluster-kfd-v1alpha2.json#L802):

```yaml
      ingress:
        # This optional key is used to override automatic parameters
        overrides:
          ingresses:
            forecastle:
              disableAuth: false
              host: forecastle.internal.example.dev
              ingressClass: alb
```
