### ISSUE TITLE
Wrong validation of `spec.distribution.modules.auth.provider`

### ISSUE THREAD

**Issue by g-iannelli** [sighupio/furyctl#257]
The following code block pass the validation

```yaml
      auth:
        provider:
          # The authentication type used for the infrastructure ingresses (all the ingress for the distribution) can be none, basicAuth, sso
          type: sso
          # configuration for the basicAuth if .spec.distribution.modules.auth.provider.type is basicAuth
          basicAuth:
            # The username
            username: admin
            # The password
            password: "{env://RANDOM}{env://RANDOM}{env://RANDOM}{env://RANDOM}{env://RANDOM}{env://RANDOM}{env://RANDOM}"
        # The base domain used for all the auth ingresses, if in the nginx dual configuration, it should be the same as the .spec.distribution.modules.ingress.dns.public.name zone
        baseDomain: internal.example.dev
        # Configuration for the pomerium package, used only if .spec.distribution.modules.auth.provider.type is sso
        #pomerium:
        #  # Additional policy configuration
        #  policy: |
        #    - from: https://myapp.example.dev
        #      to: http://myapp.svc.cluster.local:8000
        #      cors_allow_preflight: true
        #      timeout: 30s
        #  # Secrets configurations for pomerium and dex (pomerium connect to dex proxy for the SSO process)
        #  secrets:
        #    COOKIE_SECRET: "{env://KFD_AUTH_POMERIUM_COOKIE_SECRET}"
        #    IDP_CLIENT_SECRET: "{env://KFD_AUTH_POMERIUM_IDP_CLIENT_SECRET}"
        #    SHARED_SECRET: "{env://KFD_AUTH_POMERIUM_SHARED_SECRET}"
        ## Configuration for the pomerium package, used only if .spec.distribution.modules.auth.provider.type is sso
        #dex:
        #  # Dex connectors configuration
        #  connectors:
        #    - type: github
        #      id: github
        #      name: GitHub
        #      config:
        #        clientID: "{env://KFD_AUTH_DEX_CONNECTORS_GITHUB_CLIENT_ID}"
        #        clientSecret: "{env://KFD_AUTH_DEX_CONNECTORS_GITHUB_CLIENT_SECRET}"
        #        redirectURI: https://login.example.dev/callback
        #        loadAllGroups: false
        #        teamNameField: slug
        #        useLoginAsID: false


```
but it should fail because basicAuth must be [`null`](https://github.com/sighupio/fury-distribution/blob/feature/furyctl-next/schemas/ekscluster-kfd-v1alpha2.json#L1213) and `pomerium` and `dex` must not be [`null`](https://github.com/sighupio/fury-distribution/blob/feature/furyctl-next/schemas/ekscluster-kfd-v1alpha2.json#L1176)
