### ISSUE TITLE
Trailing slashes in Furyfile.yml are not properly handled

### ISSUE THREAD

**Issue by pappapisshu** [sighupio/furyctl#316]
Running `furyctl vendor --https --debug` on the `Furyfile` example file reported in `README.md`, I noticed that trailing slashes are not handled correctly.

By removing them, it works correctly.

Here is the `Furyfile` file that causes the error:
```
# Here you can specify which versions of the modules to use
versions:
  networking: v1.7.0
  monitoring: v1.13.0
  logging: v1.9.1
  ingress: v1.11.2
  dr: v1.8.0
  opa: v1.5.0

# The bases are a sets of Kustomize bases to deploy Kubernetes components
bases:
  - name: networking/
  - name: monitoring/
  - name: logging/
  - name: ingress/
  - name: dr/
  - name: opa/
```

And here is a similar `Furyfile` file, without the trailing slashes, that works correctly:
```
# Here you can specify which versions of the modules to use
versions:
  networking: v1.7.0
  monitoring: v1.13.0
  logging: v1.9.1
  ingress: v1.11.2
  dr: v1.8.0
  opa: v1.5.0

# The bases are a sets of Kustomize bases to deploy Kubernetes components
bases:
  - name: networking
  - name: monitoring
  - name: logging
  - name: ingress
  - name: dr
  - name: opa
```

I am on macOS 13.2.1 with Apple M1 Pro and here is the output of `furyctl version`:
```
INFO[0000] Furyctl version 0.9.0                        
INFO[0000] built 2022-12-22T10:49:22Z from commit 7f6d79938facf12f00d1ef4f53148a72c48f2d56
```

Here is also the output generated by `furyctl` both in the positive and in the negative case ([furyctl-ok.log](https://github.com/sighupio/furyctl/files/10873878/furyctl-ok.log) and [furyctl-ko.log](https://github.com/sighupio/furyctl/files/10873880/furyctl-ko.log), respectively).
