### ISSUE TITLE
NGINX Ingress Controller expects to find the TLS secret even if the provider is none

### ISSUE THREAD

**Issue by FedericoAntoniazzi** [sighupio/furyctl#485]
As per title, Furyctl doesn't allow creating a cluster with the ingresses available only using HTTP.

Here's the snippet of the `furyctl.yaml` I'm using.
```yaml
      ingress:
        baseDomain: minikube.demo
        nginx:
          type: single
          tls:
            provider: none
```

I'm using this for installing the distribution on my laptop.
