### ISSUE TITLE
Cannot disable MinIO on logging module

### ISSUE THREAD

**Issue by FedericoAntoniazzi** [sighupio/furyctl#486]
Hi, I was experimenting with furyctl v0.27.4 and I noticed I couldn't disable the creation MinIO instances when configuring an external endpoint.

Here's the snippet from my furyctl.yaml file:
```yaml
      logging:
        type: loki
        minio: {} # This is an attempt to disable MinIO
        loki:
          backend: externalEndpoint
          externalEndpoint:
            endpoint: minio-hot.objectstorage.svc.cluster.local:9000
            insecure: true
            bucketName: loki
            accessKeyId: minio
            secretAccessKey: minio123

```
