### ISSUE TITLE
renew certificates: add --force flag to skip serial execution on OnPremises providers

### ISSUE THREAD

**Issue by smerlos** [sighupio/furyctl#606]
**Is your feature request related to a problem? Please describe.**
Currently, `furyctl renew certificates` executes the Ansible playbook with `serial: 1` when renewing certificates on master nodes. This works well when certificates are still valid because it ensures one node is healthy before moving to the next.

However, when certificates have already expired, renewing them one by one leads to issues:
- Restarting control plane components on one node fails because quorum is broken (due to expired certs on the other masters).
- The renewal process may not complete successfully, leaving the cluster in a degraded or broken state.

**Describe the solution you’d like**
Add a `--force` flag to `furyctl renew certificates` (e.g., `furyctl renew certificates --force`) to change the playbook template generation for On-Premises providers:
- **Without** `--force`: maintain `serial: 1` to ensure stability when certs are still valid.
- **With** `--force`: omit the `serial` directive entirely so that all master nodes are processed in parallel _before_ restarting any services, ensuring expired certs across the quorum are updated together.

This lets operators choose between safe, serial renewals during routine maintenance and bulk, parallel renewals in emergency scenarios when certs have already expired.

**Describe alternatives you’ve considered**
- Keeping the current behavior (only safe for non-expired certs).
- Manually editing the generated playbook to remove `serial: 1` in emergencies.
- Introducing a generic `--parallel` flag (but `--force` better communicates override intent).

**Additional context**
This applies only to `OnPremises` providers. The playbook currently looks like:

```yaml
- name: Renew Kubernetes PKI certificates
  hosts: master,etcd
  become: true
  serial: 1           # default for safety
  tasks:
    # renewal tasks…
```

With --force, the generator would produce:
```yaml
- name: Renew Kubernetes PKI certificates
  hosts: master,etcd
  become: true
  # serial directive omitted when --force is set
  tasks:
    # renewal tasks…
```
